# Open CV
# CANNY algorithm
CANNY_KERRY_WONG_LOW_THRESHOLD_RATIO = 0.66

CANNY_RATIO_CONTROL_THRESHOLD = 0.1 / CANNY_KERRY_WONG_LOW_THRESHOLD_RATIO

CANNY_PARAM_VALUE_D = 3


CANNY_PARAM_VALUE_SIGMA_COLOR = 50

CANNY_PARAM_VALUE_SIGMA_SPACE = 50

